support eslint version 9 (flatten config)
monymony-public/monymony-eslint-config pull request #30
Opened 2024-12-09 14:33 UTC by DevYuns

### description
eslint 9를 지원하기 위해 config 설정들을 eslint 9 버전 방식(flat config)으로 마이그레이션하고, rollup으로 번들링합니다.

2024-12-09 15:11 UTC, DevYuns commented
아직 테스트가 덜되서 우선 draft로 전환합니다.

2025-01-13 06:40 UTC, DevYuns commented
cc. https://github.com/crossplatformkorea/cpk-ui/blob/main/eslint.config.cjs

2025-02-06 00:13 UTC, JeffGuKang requested changes
The version can finally be upgraded.

The code is clean. I haven't tried running it yet.
We ask that you only type a few enters at the end of the files. 👍

2025-02-06 00:13 UTC, JeffGuKang commented on backend.js
> +}];
```suggestion
}];

```

2025-02-06 00:13 UTC, JeffGuKang commented on common.js
> +);
```suggestion
);

```

2025-02-14 08:32 UTC, JeffGuKang reviewed
Do you also need execution tests?

2025-02-14 08:32 UTC, JeffGuKang commented on react.ts
> +];
```suggestion
];

```

2025-02-14 08:32 UTC, JeffGuKang commented on rollup.config.js
> +export default defineConfig([...jsConfigs, ...dtsConfigs]);
```suggestion
export default defineConfig([...jsConfigs, ...dtsConfigs]);

```

2025-02-17 01:16 UTC, DevYuns commented
@JeffGuKang I think this PR is acceptable. I found some issues in particular projects during testing, but they don’t seem to be related to this PR.

2025-04-24 02:58 UTC, JeffGuKang approved these changes
LGTM!! 👍

2025-04-24 02:58 UTC, merged